### ISSUE TITLE
New PBT Device Request - <Door/Window Sensor>

### ISSUE THREAD

**Issue by sambarlick** [MarkWattTech/Tuya-v2-Supported-Devices#11]
<table class="table">
<tr>
      <td>Security & Sensors</td>
      <td>Mirabella Genio</td>
      <td></td>
      <td>Door/Window Sensor</td>
      <td>mcs</td>
      <td>https://www.kmart.com.au/product/mirabella-genio-wi-fi-door--window-sensor/2622806</td>
      <td>Smart Wi-Fi Door & Window Sensor</td>
      <td>https://www.mirabellagenio.com.au/wp-content/uploads/2020/12/I002575-BLISTER-20190624-FOP-HR-min-1024x1024.jpg</td>
    </tr>
</table>

**Comment by MarkWattTech** [comment]
Product added. Thanks for the submission
