### ISSUE TITLE
New PBT Device Request - Motion Sensor

### ISSUE THREAD

**Issue by sambarlick** [MarkWattTech/Tuya-v2-Supported-Devices#12]
<table class="table">
<tr>
      <td>Security & Sensors</td>
      <td>Mirabella Genio/td>
      <td></td>
      <td>Motion Sensor</td>
      <td>pir</td>
      <td>https://www.kmart.com.au/product/mirabella-genio-wi-fi-motion-sensor/2622811</td>
      <td>Smart Wi-Fi Motion Sensor</td>
      <td>https://www.kmart.com.au/wcsstore/Kmart/images/ncatalog/f/3/42769453-2-f.jpg</td>
    </tr>
</table>

**Comment by MarkWattTech** [comment]
Product added thanks Sam.
