### ISSUE TITLE
New PBT Device Request - <Your Product Name>

### ISSUE THREAD

**Issue by finalbillybong** [MarkWattTech/Tuya-v2-Supported-Devices#18]
**I'm currently documenting everything in a simple HTML table**
 If you can provide me with all of the following information I will add the product to the list :

<table class="table">
<tr>
      <td>Large Home Appliance</td>
      <td>Igenix</td>
      <td>IG9909WIFI</td>
      <td>Air conditioner</td>
      <td>kt</td>
      <td>https://www.amazon.co.uk/dp/B095HTVV36/?coliid=I3W5D3BBVBGA9J&colid=2FYVB5AEMBPTD&psc=1&ref_=lv_ov_lig_dp_it</td>
      <td> Air Conditioning Unit</td>
      <td>https://images.app.goo.gl/1SzBUTvzCgEjRawV6</td>
    </tr>
</table>

**Comment by MarkWattTech** [comment]
Product has been added thank you!
Be sure to change the submission title next time :)
