### ISSUE TITLE
New PBT Device Request - <Ambiance Bulb>

### ISSUE THREAD

**Issue by twanjaarsveld** [MarkWattTech/Tuya-v2-Supported-Devices#20]
<table class="table">
<tr>
      <td>Lights</td>
      <td>LSC (Action)</td>
      <td>A60 CCT</td>
      <td>Lights</td>
      <td>dj</td>
      <td>https://www.action.com/nl-nl/p/lsc-smart-connect-slimme-ledlamp3//</td>
      <td>Cheap Ambiance E27 bulb </td>
      <td>https://www.action.com/globalassets/cmsarticleimages/75/96/3000272_8712879146254-111.png?preset=mediaSliderImageLargeHD</td>
    </tr>
</table>

**Comment by MarkWattTech** [comment]
product has been added
