### ISSUE TITLE
New PBT Device Request - <LSC Neon led strip>

### ISSUE THREAD

**Issue by twanjaarsveld** [MarkWattTech/Tuya-v2-Supported-Devices#21]
<table class="table">
<tr>
      <td>Lighting</td>
      <td>LSC (Action)</td>
      <td> neon ledstrip</td>
      <td>Light</td>
      <td>dj</td>
      <td>https://www.action.com/nl-nl/p/lsc-smart-connect-neon-ledstrip/</td>
      <td>Smart RGB Neon Ledstrip</td>
      <td>https://www.action.com/globalassets/cmsarticleimages/23/80/3005457_8712879149163-111_01.png?preset=mediaSliderImageLargeHD</td>
    </tr>
</table>

**Comment by MarkWattTech** [comment]
Product added

**Comment by twanjaarsveld** [comment]
I see now that i probably used the wrong Product code as "dj" is just for normal lights

**Comment by twanjaarsveld** [comment]
Should have been dd
