### ISSUE TITLE
New PBT Device Request - <LSC smart socket>

### ISSUE THREAD

**Issue by twanjaarsveld** [MarkWattTech/Tuya-v2-Supported-Devices#22]
<table class="table">
<tr>
      <td>Electrician Category</td>
      <td>LSC (Action)</td>
      <td>The model for device (if applicable)</td>
      <td> Socket </td>
      <td> cz </td>
      <td>https://www.action.com/nl-nl/p/lsc-smart-connect-slimme-stekker-/</td>
      <td>Cheap Wifi smart socket</td>
      <td>https://www.action.com/globalassets/cmsarticleimages/79/98/2578685_8712879142782-111.png?preset=mediaSliderImageLargeHD</td>
    </tr>
</table>

**Comment by MarkWattTech** [comment]
Product has been added
