### ISSUE TITLE
New PBT Device Request - <RGB Spot>

### ISSUE THREAD

**Issue by twanjaarsveld** [MarkWattTech/Tuya-v2-Supported-Devices#23]
<table class="table">
<tr>
      <td>Lightning</td>
      <td>LSC (Action)</td>
      <td>LedSpot</td>
      <td>Light</td>
      <td>dj</td>
      <td>https://www.action.com/nl-nl/p/lsc-smart-connect-led-spot/</td>
      <td>Cheap RGB smart spot</td>
      <td>https://www.action.com/globalassets/cmsarticleimages/26/37/3005365_8712879149095-111_01.png?preset=mediaSliderImageLargeHD</td>
    </tr>
</table>

**Comment by MarkWattTech** [comment]
Product added. Thanks for taking the time to submit all of these mate. Filled in perfectly!
