### ISSUE TITLE
New PBT Device Request - <Your Product Name>

### ISSUE THREAD

**Issue by Aresitoo** [MarkWattTech/Tuya-v2-Supported-Devices#24]
<table class="table">
<tr>
      <td>Security & Sensors</td>
      <td>SONOFF</td>
      <td>snzb - 03</td>
      <td>pir</td>
      <td>PIR Detector</td>
      <td>https://www.ebay.es/itm/324235275970</td>
      <td> Zigbee PIR Detector</td>
      <td>https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlfQhV9KeujQGyBY29iklZbM3aT0PH1wH4Jg&usqp=CAU</td>
    </tr>
</table>

**Comment by MarkWattTech** [comment]
Please fill in the product title next time :D
Thanks for submitting

**Comment by MarkWattTech** [comment]
Product has been added

**Comment by Aresitoo** [comment]
oups! forgot that one
