### ISSUE TITLE
New PBT Device Request - <Garden RGB Pole>

### ISSUE THREAD

**Issue by twanjaarsveld** [MarkWattTech/Tuya-v2-Supported-Devices#25]
<table class="table">
<tr>
      <td>Lightning</td>
      <td>LSC Action</td>
      <td>Garden pole</td>
      <td>Light</td>
      <td>dj</td>
      <td>https://www.action.com/nl-nl/p/lsc-smart-connect-led-tuinlamp/</td>
      <td>Cheap RGB Garden pole </td>
      <td>https://www.action.com/globalassets/cmsarticleimages/26/39/3005364_8712879149088-111_01.png?preset=mediaSliderImageLargeHD</td>
    </tr>
</table>

**Comment by MarkWattTech** [comment]
Product has been added
