### ISSUE TITLE
New PBT Device Request - <Big Filament Bulb >

### ISSUE THREAD

**Issue by twanjaarsveld** [MarkWattTech/Tuya-v2-Supported-Devices#27]
<table class="table">
<tr>
      <td>Lightning</td>
      <td>LSC (Action)</td>
      <td>E27 Filament</td>
      <td>Light</td>
      <td>dj</td>
      <td>https://www.action.com/nl-nl/p/lsc-smart-connect-slimme-filament-ledlamp4/</td>
      <td>Big RGB Bulb </td>
      <td>https://www.action.com/globalassets/cmsarticleimages/00/25/3001700_8712879146629-111.png?preset=mediaSliderImageLargeHD</td>
    </tr>
</table>

**Comment by MarkWattTech** [comment]
Added to list
