### ISSUE TITLE
New PBT Device Request - <Small Filament Bulb >

### ISSUE THREAD

**Issue by twanjaarsveld** [MarkWattTech/Tuya-v2-Supported-Devices#28]
<table class="table">
<tr>
      <td>Lightning</td>
      <td>LSC (Action)</td>
      <td>E27 Small bulb</td>
      <td>Light</td>
      <td>dj</td>
      <td>https://www.action.com/nl-nl/p/lsc-smart-connect-slimme-filament-ledlamp2//</td>
      <td>E27 Small Filament bulb </td>
      <td>https://www.action.com/globalassets/cmsarticleimages/28/58/3001686_8712879146605-111.png?preset=mediaSliderImageLargeHD</td>
    </tr>
</table>

**Comment by MarkWattTech** [comment]
Product added thanks again!
