### ISSUE TITLE
New PBT Device Request - <e14 Filament bulb>

### ISSUE THREAD

**Issue by twanjaarsveld** [MarkWattTech/Tuya-v2-Supported-Devices#29]
<table class="table">
<tr>
      <td>Lightning</td>
      <td>LSC (Action)</td>
      <td>E14 Filament</td>
      <td>light</td>
      <td>dj</td>
      <td>https://www.action.com/nl-nl/p/lsc-smart-connect-slimme-filament-ledlamp3//</td>
      <td> E14 Small filament bulb</td>
      <td>https://www.action.com/globalassets/cmsarticleimages/66/12/3001702_8712879146612-111.png?preset=mediaSliderImageLargeHD</td>
    </tr>
</table>

**Comment by MarkWattTech** [comment]
Product added thank you!
