### ISSUE TITLE
New PBT Device Request - <GU10 light>

### ISSUE THREAD

**Issue by twanjaarsveld** [MarkWattTech/Tuya-v2-Supported-Devices#30]
<table class="table">
<tr>
      <td>Lightning</td>
      <td>LSC (Action)</td>
      <td>GU10 Ambiance</td>
      <td>light</td>
      <td>dj</td>
      <td>https://www.action.com/nl-nl/p/lsc-smart-connect-slimme-ledlamp/</td>
      <td>Cheap Ambiance GU10 bulb</td>
      <td>https://www.action.com/globalassets/cmsarticleimages/76/02/3000267_8712879146223-111.png?preset=mediaSliderImageLargeHD</td>
    </tr>
</table>

**Comment by MarkWattTech** [comment]
Product Added thank you!
