### ISSUE TITLE
New PBT Device Request - <RGB outside wall light>

### ISSUE THREAD

**Issue by twanjaarsveld** [MarkWattTech/Tuya-v2-Supported-Devices#31]
<table class="table">
<tr>
      <td>Lightning</td>
      <td>LSC (Action)</td>
      <td>RGB Wall light</td>
      <td>Light</td>
      <td>dj</td>
      <td>https://www.action.com/nl-nl/p/lsc-smart-connect-wandlamp/</td>
      <td>RGB outside wall light </td>
      <td>https://www.action.com/globalassets/cmsarticleimages/26/32/3005447_8712879149101-111_01.png?preset=mediaSliderImageLargeHD</td>
    </tr>
</table>

**Comment by MarkWattTech** [comment]
Product added to list :)
