### ISSUE TITLE
New PBT Device Request - <RGB e14 bulb>

### ISSUE THREAD

**Issue by twanjaarsveld** [MarkWattTech/Tuya-v2-Supported-Devices#32]
<table class="table">
<tr>
      <td>LIghtning</td>
      <td>LSC (Action)</td>
      <td>RGB e14</td>
      <td>Light</td>
      <td>dj</td>
      <td>https://www.action.com/nl-nl/p/lsc-smart-connect-slimme-multicolor-ledlamp2/</td>
      <td>RGB E14 Bulb </td>
      <td>https://www.action.com/globalassets/cmsarticleimages/64/53/3004164_8712879146582-111_02.png?preset=mediaSliderImageLargeHD</td>
    </tr>
</table>

**Comment by MarkWattTech** [comment]
Product added. Thank you for submitting!

**Comment by twanjaarsveld** [comment]
> Product

Love to help out
