### ISSUE TITLE
New PBT Device Request - ZMAi 90

### ISSUE THREAD

**Issue by tsiaGeorge** [MarkWattTech/Tuya-v2-Supported-Devices#4]
<table class="table">
<tr>
      <td>Energy</td>
      <td>Unknown</td>
      <td>ZMAi 90</td>
      <td>Smart Electricity Meter</td>
      <td>zndb</td>
      <td>https://www.aliexpress.com/item/4001053795800.html?spm=a2g0o.productlist.0.0.29283155WwcdGn&algo_pvid=a220b732-e380-4326-8c22-45f983319ca0&algo_exp_id=a220b732-e380-4326-8c22-45f983319ca0-0&pdp_ext_f=%7B%22sku_id%22%3A%2212000018708063957%22%7D</td>
      <td>WiFi Smart Switch Energy Meter</td>
      <td>http://ae01.alicdn.com/kf/Hfe2166313e554b359b6df1b35b0c7278r.jpg</td>
    </tr>
</table>

**Comment by MarkWattTech** [comment]
Product has been added. Thank you for contributing 👍
