### ISSUE TITLE
New PBT Device Request - Avatar ALS15L

### ISSUE THREAD

**Issue by alessio-papi** [MarkWattTech/Tuya-v2-Supported-Devices#5]
<table class="table">
<tr>
      <td>Lighting</td>
      <td>Avatar controls</td>
      <td>ALS15L</td>
      <td>Light</td>
      <td>dj</td>
      <td>https://www.amazon.it/Intelligence-Compatibile-Avatar-Controls-Multicolore/dp/B07W6Z6KPG/ref=pd_lpo_1?pd_rd_i=B07W6Z6KPG&psc=1</td>
      <td>A RBGW B14 bulb</td>
      <td>https://www.avatarcontrols.com/upfile/2019/07/20190709175532_974.jpg</td>
</tr>
</table>

**Comment by MarkWattTech** [comment]
Thank you for the submission Alessio.
Product has been added to the list.
