### ISSUE TITLE
New PBT Device Request - Avatto D06 Door Window sensor

### ISSUE THREAD

**Issue by molnarti** [MarkWattTech/Tuya-v2-Supported-Devices#6]
**I'm currently documenting everything in a simple HTML table**
 If you can provide me with all of the following information I will add the product to the list :

<table class="table">
<tr>
      <td>Security & Sensors</td>
      <td>Avatto</td>
      <td>D06</td>
      <td>Door Window Sensor</td>
      <td>mcs</td>
      <td>https://www.aliexpress.com/item/4000790781739.html?spm=a2g0s.9042311.0.0.27424c4dZ9ti8B</td>
      <td>WIFI door or window opening sensor operated by 2 AA batteries. </td>
      <td>https://ae01.alicdn.com/kf/H87ba7222b6fa41e591860fcbc1f40080j/AVATTO-Tuya-WiFi-Door-Sensor-Smart-Door-Open-Closed-Detectors-Smartlife-APP-Wifi-Window-Sensor-Work.jpg_640x640.jpg</td>
    </tr>
</table>

**Comment by MarkWattTech** [comment]
Thank you for the submission! Product has been added.
