### ISSUE TITLE
New PBT Device Request - noname Tuya Wifi Smart socket

### ISSUE THREAD

**Issue by molnarti** [MarkWattTech/Tuya-v2-Supported-Devices#7]
<table class="table">
<tr>
      <td>Electrician Category</td>
      <td>unknown</td>
      <td>unknown</td>
      <td>Socket</td>
      <td>cz</td>
      <td>https://www.aliexpress.com/item/4000478798085.html?spm=a2g0s.9042311.0.0.27424c4dZ9ti8B/</td>
      <td>16A wifi smart socket with power monitoring (Note: uses non-ESP chipset, cannot be flashed to ESPhome or Tasmota)</td>
      <td>![image](https://user-images.githubusercontent.com/25829862/129449914-40c56d36-c352-480d-a3d1-d479f00c63a4.png)</td>
    </tr>
</table>

**Comment by MarkWattTech** [comment]
Thank you for the submission. Great description!
