### ISSUE TITLE
New PBT Device Request - Mirabella Genio 9w Downlight 

### ISSUE THREAD

**Issue by alfa324372** [MarkWattTech/Tuya-v2-Supported-Devices#8]
**I'm currently documenting everything in a simple HTML table**
 If you can provide me with all of the following information I will add the product to the list :

<table class="table">
<tr>
      <td>Light</td>
      <td>Mirabella Genio</td>
      <td>9w color downlight</td>
      <td>Lighting</td>
      <td>Dj</td>
      <td>https://www.kmart.com.au/product/mirabella-genio-9w-led-wi-fi-dimmable-downlight/2754330</td>
      <td> RGBW Downlight</td>
      <td>https://www.kmart.com.au/product/mirabella-genio-9w-led-wi-fi-dimmable-downlight/2754330</td>
    </tr>
</table>

**Comment by MarkWattTech** [comment]
Product added. Thank you for contributing.
