### ISSUE TITLE
New PBT Device Request - <LVWIT A60 Tuya Smart Bulb B22>

### ISSUE THREAD

**Issue by markvader** [MarkWattTech/Tuya-v2-Supported-Devices#9]
<table class="table">
<tr>
      <td>Lighting</td>
      <td>LVWIT</td>
      <td>A60</td>
      <td>Light</td>
      <td>dj</td> <td>https://www.amazon.co.uk/dp/B08315XSXS/ref=cm_sw_r_cp_apa_glt_fabc_06BKQZ357MY8ZZ0AMS35?_encoding=UTF8&psc=1</td>
      <td>Tuya RGB Smart Bulb B22</td>
      <td>https://cdn.shopify.com/s/files/1/0257/5790/9044/products/51KDIzDdR2L._AC_SL1300_c92de931-bbb3-4d69-bb7d-f444be165486_997x1066.jpg?v=1589193477</td>
    </tr>
</table>

**Comment by MarkWattTech** [comment]
Product added. Thanks for submitting mark!
